FROM node:20-alpine

WORKDIR /app

# Copy package files first to leverage caching
COPY package*.json .
RUN npm install

# Copy the rest of the frontend source code
COPY . .

# Expose Angular's default port
EXPOSE 4200

# Run angular dev server with host check disabled so it's accessible outside the container
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]